[control_plane]
control-plane ansible_host=<server_ip> ansible_user=<server_username> wireguard_ip=10.8.0.1

[workers]
# for the foreseeable future this will probably be empty as the cluster can function fine with only one server

[k3s_cluster:children]
control_plane
workers

[kiosks]
kiosk-1 ansible_host=<kiosk_1_ip> ansible_user=<kiosk_username> wireguard_ip=10.8.0.101
kiosk-2 ansible_host=<kiosk_2_ip> ansible_user=<kiosk_username> wireguard_ip=10.8.0.102
